version: '3.8'

services:
  app:
    build: .
    container_name: app
    # The app listens on 8080 internally
    # We don't need to expose 8080 to the host since Nginx will handle external traffic.
    depends_on:
      - postgres
    command: ["/wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/bs-api.desperate.dk/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/bs-api.desperate.dk/privkey.pem:/etc/ssl/private/privkey.pem:ro


volumes:
  postgres_data:

networks:
  default:
    name: my_network
